name: duck-TV
version: "0.3.1"
slug: duck-TV
description: Full media control by voice! Powered by DuckDNS & duck-TV!
url: "https://github.com/pungkula1337anka/ha-addons/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
